name: chatline_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.14
  flutter_iconly: ^1.0.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  iconsax: ^0.0.8
  string_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/gift/
    - assets/icon/
    - assets/font/
    - assets/media/
    - assets/person/

  fonts:
    - family: SF
      fonts:
        - asset: assets/font/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/font/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/font/SFPRODISPLAYREGULAR.OTF
          weight: 400